---
- name: Install Applications
  hosts: localhost
  become: false
  tasks:
    - name: Install GIMP
      homebrew_cask:
        name: "gimp"
        state: present

    - name: Install Apache Directory Studio
      homebrew_cask:
        name: "apache-directory-studio"
        state: present

