---
- name: Update ENV for BASH and ZSH
  hosts: localhost
  become: false
  tasks:
    - name: Set Python Keystore Path in .bashrc
      become: true
      lineinfile:
        path: "/etc/bashrc"
        regexp: '^export REQUESTS_CA_BUNDLE=.*$'
        line: 'export REQUESTS_CA_BUNDLE=/Library/Certificates/allcerts.pem'
        state: present
        create: true

    - name: Set Python Keystore Path in .bashrc
      become: false
      lineinfile:
        path: "{{ local_user_homedir }}/.zshrc"
        regexp: '^export REQUESTS_CA_BUNDLE=.*$'
        line: 'export REQUESTS_CA_BUNDLE=/Library/Certificates/allcerts.pem'
        state: present
        create: true

